# Generated by Django 2.1 on 2018-08-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180806_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date_modified',
        ),
    ]
